# Default initial positions for automail's ros2_control fake system

initial_positions:
  joint1_base_rotation: 0
  joint2_shoulder_pitch: 0
  joint3_elbow_pitch: 0
  joint4_wrist_roll: 0
  joint5_wrist_pitch: 0
  joint_finger_left: 0
  joint_finger_right: 0